-- ==============================================================================
-- Matheopolis - Quiz: L'Histoire de Laurence
-- Generated from matheopolis.json
-- ==============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Insert the Quiz
INSERT INTO `quizzes` (`id`, `title`, `description`, `creator_id`, `status`, `ask_admin`, `position`, `created_at`)
VALUES (999, 'L\'Histoire de Laurence', 'Testez vos connaissances sur le livre.', 0, 'public', FALSE, 0, '2026-05-22 00:00:00');

-- 2. Insert Questions and Options
-- Using the IDs from the JSON to ensure consistency

INSERT INTO `quiz_questions` (`id`, `quiz_id`, `label`, `order_index`, `type`) VALUES
(1, 999, 'Comment s\'appelle le personnage principal ?', 0, 'radio'),
(2, 999, 'Quel âge a le personnage principal aujourd\'hui ?', 1, 'radio'),
(3, 999, 'Le narrateur prétend avoir résolu le problème de la conjecture de Golbach. En récompense de cet exploit, elle a touché :', 2, 'radio'),
(4, 999, 'Depuis des années, le narrateur :', 3, 'radio'),
(5, 999, 'Qu\'est-il arrivé à ses parents ?', 4, 'radio'),
(6, 999, 'Où vit-elle depuis octobre 2009 ?', 5, 'radio'),
(7, 999, 'De quel étrange pouvoir dispose-t-elle ?', 6, 'radio'),
(8, 999, 'Quelle a été la conséquence scolaire de ce nouveau pouvoir ?', 7, 'radio'),
(9, 999, 'Que cherche à faire le narrateur ?', 8, 'radio'),
(10, 999, 'Laurence conseille de lire Mathéopolis', 9, 'radio'),
(11, 999, 'Comment Laurence aborde-t-elle ses devoirs de mathématiques ?', 10, 'radio'),
(12, 999, 'Où Laurence vit-elle ?', 11, 'radio'),
(13, 999, 'Sur quoi Laurence travaille-t-elle ?', 12, 'radio'),
(14, 999, 'Comment le grand-père s\'appelle-il ?', 13, 'radio'),
(15, 999, 'D\'après le grand-père, Laurence tient entre ses mains :', 14, 'radio'),
(16, 999, 'Quelle est la réaction de Laurence face à son travail ?', 15, 'radio'),
(17, 999, 'Quel est l\'objet que présente le grand-père à Laurence ?', 16, 'radio'),
(18, 999, 'Que comporte le livre que lui présente son grand-père ?', 17, 'radio'),
(19, 999, 'Le grand-père sort de ce livre :', 18, 'radio'),
(20, 999, 'Quel est le point commun entre tous les documents observés par Laurence à la demande du grand-père ?', 19, 'radio'),
(21, 999, 'Dans quel but le grand-père lui présente-t-il ces documents ?', 20, 'radio'),
(22, 999, 'Le grand-père demande à Laurence de tracer :', 21, 'radio'),
(23, 999, 'On dit qu\'une droite est :', 22, 'radio'),
(24, 999, 'Laurence découvre que le point qu\'elle a tracé :', 23, 'radio'),
(25, 999, 'Avec la droite et le point, Laurence comprend que les vraies figures géométriques sont :', 24, 'radio'),
(26, 999, 'Laurence et son grand-père prennent la voiture pour :', 25, 'radio'),
(27, 999, 'En regardant les étoiles, Laurence découvre :', 26, 'radio'),
(28, 999, 'Platon avait fait inscrire sur le fronton de son Académie', 27, 'radio'),
(29, 999, 'Le savant Galilée pense que :', 28, 'radio'),
(30, 999, 'L\'exercice de Laurence :', 29, 'radio'),
(31, 999, 'Laurence se demande si la géométrie est :', 30, 'radio'),
(32, 999, 'Laurence pense que les nombres :', 31, 'radio'),
(33, 999, 'Pourquoi le grand-père décroche-t-il un filet de pêche ?', 32, 'radio'),
(34, 999, 'Laurence commet l\'erreur :', 33, 'radio'),
(35, 999, 'Le grand-père montre à Laurence dans le carnet :', 34, 'radio'),
(36, 999, 'Indique le chiffre le plus grand:', 35, 'radio'),
(37, 999, 'Les nombres 1, 2, 3, etc. s\'appellent:', 36, 'radio'),
(38, 999, 'Les nombres négatifs :', 37, 'radio'),
(39, 999, 'Un nombre imaginaire est :', 38, 'radio'),
(40, 999, 'Pour le développement des mathématiques à travers l\'Histoire :', 39, 'radio'),
(41, 999, 'Les hommes préhistoriques', 40, 'radio'),
(42, 999, 'L\'écriture humaine remonte à', 41, 'radio'),
(43, 999, 'Les premières figures géométriques datent', 42, 'radio'),
(44, 999, 'Une civilisation ancienne comptait par \"paquets de 60\". Ce sont', 43, 'radio'),
(45, 999, 'Thalès de Milet est', 44, 'radio'),
(46, 999, 'Grâce aux mathématiques, les savants grecs', 45, 'radio'),
(47, 999, 'On peut faire remonter la recherche de vérités universelles par le raisonnement', 46, 'radio'),
(48, 999, 'Pour Thalès et Pythagore, la réalité est', 47, 'radio'),
(49, 999, 'Pour Pythagore, la formule qui résumerait la structure profonde de l\'univers est', 48, 'radio'),
(50, 999, 'Pour noter les nombres décimaux, par exemple \"1,8\", les Grecs', 49, 'radio'),
(51, 999, 'Un nombre irrationnel, est', 50, 'radio'),
(52, 999, 'Les savants grecs', 51, 'radio'),
(53, 999, 'Dans la Grèce antique, un philosophe est', 52, 'radio'),
(54, 999, 'La capitale scientifique, artistique et littéraire de la Grèce antique était', 53, 'radio'),
(55, 999, 'L\'Académie de Platon est', 54, 'radio'),
(56, 999, 'Pour Platon et d\'autres savants grecs, la réalité', 55, 'radio'),
(57, 999, 'Les savants romains qui écrivaient en latin', 56, 'radio'),
(58, 999, 'Au moment des invasions barbares et pendant les siècles qui ont suivi', 57, 'radio'),
(59, 999, 'Le père de Laurence voyageait beaucoup', 58, 'radio'),
(60, 999, 'Les carnets du père de Laurence', 59, 'radio'),
(61, 999, 'Après Athènes, la capitale scientifique du monde est', 60, 'radio'),
(62, 999, 'Le savant Archimède est mort', 61, 'radio'),
(63, 999, 'Euclide est', 62, 'radio'),
(64, 999, 'La grande bibliothèque d\'Alexandrie a été', 63, 'radio'),
(65, 999, 'La grande ville du monde arabe qui peut être considérée comme une capitale scientifique au Moyen Age est', 64, 'radio'),
(66, 999, 'Une des plus grandes inventions mathématiques apportées par les savants arabes est', 65, 'radio'),
(67, 999, 'Bagdad est une capitale scientifique', 66, 'radio'),
(68, 999, 'Les savants de l\'Inde ancienne', 67, 'radio'),
(69, 999, 'L\'origine du mot \"chiffre\" est', 68, 'radio'),
(70, 999, 'Pour l\'histoire des sciences et l\'avenir de l\'humanité, l\'invention de la numération indo-arabe', 69, 'radio'),
(71, 999, 'La science grecque et arabe gagne l\'Europe au Moyen Age', 70, 'radio'),
(72, 999, 'Le Moyen Age latin, surtout en France, connaît une véritable Renaissance', 71, 'radio'),
(73, 999, 'Pour les savants chrétiens du Moyen Age, les mathématiques', 72, 'radio'),
(74, 999, 'Fibonacci est le nom', 73, 'radio'),
(75, 999, 'La ville de Constantinople, appelée aussi Byzance, est envahie en 1453', 74, 'radio'),
(76, 999, 'La période qui s\'ouvre en Europe au XVe siècle s\'appelle', 75, 'radio'),
(77, 999, 'Après la prise de Constantinople, l\'Europe découvre', 76, 'radio'),
(78, 999, 'Le savant de la Renaissance, souvent italien, est', 77, 'radio'),
(79, 999, 'Cardan et Tartaglia sont', 78, 'radio'),
(80, 999, 'Les signes mathématiques que nous utilisons aujourd\'hui \"+\", \"-\", \"=\", \"<\", \">\", \"x\"', 79, 'radio'),
(81, 999, 'Dans l\'histoire des sciences, l\'invention du calcul littéral, en particulier de la lettre x', 80, 'radio'),
(82, 999, 'L\'inventeur de la lettre x pour désigner une inconnue dans le calcul littéral s\'appelle', 81, 'radio'),
(83, 999, 'L\'algèbre est', 82, 'radio'),
(84, 999, 'Le savant Newton écrit une formule mathématique pour', 83, 'radio'),
(85, 999, 'A partir de la fin du XVIIe siècle, pour étudier la nature, le langage mathématique', 84, 'radio'),
(86, 999, 'Grâce aux mathématiques et à l\'invention de nouvelles théories, on peut', 85, 'radio'),
(87, 999, 'Par rapport à l\'expérimentation et à l\'observation, les formules mathématiques des plus grands savants du XXe siècle sont', 86, 'radio'),
(88, 999, 'D\'après la théorie M des supercordes, notre monde aurait', 87, 'radio'),
(89, 999, 'Les mathématiques aujourd\'hui permettent', 88, 'radio'),
(90, 999, 'On peut utiliser les mathématiques en cancérologie principalement pour', 89, 'radio'),
(91, 999, 'En octobre 2009, Laurence', 90, 'radio'),
(92, 999, 'Laurence a compris que', 91, 'radio'),
(93, 999, 'A partir d\'octobre 2009, Laurence se met', 92, 'radio'),
(94, 999, 'Goldbach est :', 93, 'radio'),
(95, 999, 'Gödel est:', 94, 'radio'),
(96, 999, 'Le théorème de Goldbach', 95, 'radio'),
(97, 999, 'Laurence', 96, 'radio'),
(98, 999, 'Mathéopolis', 97, 'radio'),
(99, 999, 'Laurence', 98, 'radio'),
(100, 999, 'Francis Loret, Pierre Seguin et Fabrice Lli sont', 99, 'radio');

INSERT INTO `quiz_options` (`id`, `question_id`, `label`, `is_correct`) VALUES
(11, 1, 'Laurence Guéret', FALSE), (12, 1, 'Mathéopolis', FALSE), (13, 1, 'Lawrence d\'Arabie', FALSE), (14, 1, 'Laurence Guerney', TRUE),
(21, 2, 'un plus', FALSE), (22, 2, '14 ans', FALSE), (23, 2, '35 ans', FALSE), (24, 2, '25 ans', TRUE),
(31, 3, 'deux millions de dollars', FALSE), (32, 3, 'un million de dollars', TRUE), (33, 3, 'rien du tout', FALSE), (34, 3, 'au Grisby', FALSE),
(41, 4, 'est une célébrité invitée dans l\'émission les Marseillais', FALSE), (42, 4, 'est un biologiste', FALSE), (43, 4, 'est en fuite et se cache', TRUE), (44, 4, 'fabrique ses propres maquettes en allumettes', FALSE),
(51, 5, 'ils ont divorcé', FALSE), (52, 5, 'ils ont joué ensemble dans Plus belle la vie', FALSE), (53, 5, 'sa mère est décédée et son père a disparu', TRUE), (54, 5, 'ils sont partis faire le tour du monde à la voile', FALSE),
(61, 6, 'chez sa tante Quéchoix', FALSE), (62, 6, 'chez son grand-père', TRUE), (63, 6, 'avec son père', FALSE), (64, 6, 'dans un cirque ambulant', FALSE),
(71, 7, 'elle voit le monde mathématique aussi clairement que le monde réel', TRUE), (72, 7, 'elle peut prévoir le futur et même le tirage de l\'Euro Million', FALSE), (73, 7, 'c\'est une élève surdouée qui est la meilleure dans toutes les disciplines', FALSE), (74, 7, 'elle peut se transformer en n\'importe quoi comme Mystic dans les X-men', FALSE),
(81, 8, 'Laurence a complètement cessé de travailler à l\'école', FALSE), (82, 8, 'ses résultats se sont améliorés de manière spectaculaire', TRUE), (83, 8, 'elle a battu un record de vitesse manducatoire à la cantine', FALSE), (84, 8, 'elle a définitivement égaré son agenda sur lequel il y avait un mustang au galop', FALSE),
(91, 9, 'transmettre au monde entier le moyen d\'acquérir ce pouvoir', FALSE), (92, 9, 'utiliser les mathématiques pour communiquer avec les dauphins', FALSE), (93, 9, 'cacher ce secret au monde entier', TRUE), (94, 9, 's\'enrichir grâce à son pouvoir', FALSE),
(101, 10, 'pour passer le temps', FALSE), (102, 10, 'pour acquérir le même pouvoir qu\'elle', TRUE), (103, 10, 'pour respecter le traité passé avec les Yanomami d\'Amazonie', FALSE), (104, 10, 'pour améliorer son sens de l\'orientation', FALSE),
(111, 11, 'en souriant', FALSE), (112, 11, 'en tongs et en maillot de bain, prête à aller à la plage', FALSE), (113, 11, 'à contre-cœur', TRUE), (114, 11, 'en mangeant des biscuits à la praline', FALSE),
(121, 12, 'à Marseille chez son grand-père', TRUE), (122, 12, 'à Marseille toute seule dans les vestiaires du stade vélodrome', FALSE), (123, 12, 'dans une auberge de jeunesse, quartier Bonneveine', FALSE), (124, 12, 'juste là-bas à côté de la boulangerie en face de l\'église', FALSE),
(131, 13, 'sur une planche à repasser', FALSE), (132, 13, 'sur le théorème de Thalès', TRUE), (133, 13, 'sur le théorème de Pythagore', FALSE), (134, 13, 'Sur un exercice d\'architecture en pachtoune', FALSE),
(141, 14, 'Thalès', FALSE), (142, 14, 'Papi Mouzo', FALSE), (143, 14, 'Papé Thomasaïne.', TRUE), (144, 14, 'Ezio Auditore', FALSE),
(151, 15, 'un stylo à encre sympathique', FALSE), (152, 15, 'des instruments chirurgicaux', FALSE), (153, 15, 'des outils comme les autres', FALSE), (154, 15, 'un trésor qui vaut plus que de l\'or', TRUE),
(161, 16, 'elle est passionnée', FALSE), (162, 16, 'elle n\'en voit ni l\'utilité ni l\'intérêt', TRUE), (163, 16, 'elle le fait sans se poser de question', FALSE), (164, 16, 'elle allume l\'émission de Hanouna sur C8', FALSE),
(171, 17, 'un marteau', FALSE), (172, 17, 'un compas', FALSE), (173, 17, 'les carnets de voyage de son père', TRUE), (174, 17, 'une perceuse sans fil', FALSE),
(181, 18, 'uniquement des formules mathématiques', FALSE), (182, 18, 'des poèmes en kyniarwanda', FALSE), (183, 18, 'des dessins et des cartes de pays imaginaires pour réaliser un jeu d\'héroïc fantasy', FALSE), (184, 18, 'Toutes sortes d\'éléments: dessins, photos, cartes, remarques, symboles, etc.', TRUE),
(191, 19, 'des figures géométriques', FALSE), (192, 19, 'une liasse de factures', FALSE), (193, 19, 'un lapin blanc', FALSE), (194, 19, 'des remarques personnelles', TRUE),
(201, 20, 'ce sont des dessins trompeurs, appelés illusions d\'optique', TRUE), (202, 20, 'ce sont des figures géométriques qui donnent la solution à son exercice', FALSE), (203, 20, 'ce sont des publicités pour une agence de voyage', FALSE), (204, 20, 'ce sont des documents qui n\'ont aucun rapport entre eux', FALSE),
(211, 21, 'pour lui montrer que la géométrie n\'a aucun intérêt', FALSE), (212, 21, 'pour lui montrer qu\'elle ne peut pas faire confiance à ses yeux', TRUE), (213, 21, 'pour la défense des bancs de corail hawaïens', FALSE), (214, 21, 'pour lui apprendre à mieux se repérer dans une zone d\'inconfort tridimensionnelle', FALSE),
(221, 22, 'un triangle', FALSE), (222, 22, 'le plus loin possible', FALSE), (223, 22, 'le dessin qu\'elle veut mais avec beaucoup de jolies couleurs', FALSE), (224, 22, 'une droite', TRUE),
(231, 23, 'infinie', TRUE), (232, 23, 'finie d\'un seul côté', FALSE), (233, 23, 'finie quand elle est tracée', FALSE), (234, 23, 'à l\'envers si on la regarde longtemps', FALSE),
(241, 24, 'est parfait', FALSE), (242, 24, 'n\'est pas un vrai point géométrique', TRUE), (243, 24, 'est beaucoup trop petit', FALSE), (244, 24, 'est noir', FALSE),
(251, 25, 'très faciles à tracer', FALSE), (252, 25, 'en réalité invisibles', TRUE), (253, 25, 'des dessins très jolis', FALSE), (254, 25, 'des objets trouvés dans une brocante', FALSE),
(261, 26, 'aller en Suisse', FALSE), (262, 26, 'faire le plein d\'essence', FALSE), (263, 26, 'tester les pneus tout neufs', FALSE), (264, 26, 'contempler le ciel au bord de la mer', TRUE),
(271, 27, 'des figures géométriques', TRUE), (272, 27, 'une navette spatiale', FALSE), (273, 27, 'qu\'elle perd son temps', FALSE), (274, 27, 'le portrait de Thalès', FALSE),
(281, 28, 'carpe Diem', FALSE), (282, 28, 'que nul n\'entre ici s\'il n\'est géomètre', TRUE), (283, 28, 'droit au but', FALSE), (284, 28, 'je pense, donc je suis', FALSE),
(291, 29, 'le monde obéit au hasard', FALSE), (292, 29, 'les mathématiques sont inutiles', FALSE), (293, 29, 'l\'univers est un gros caillou en forme de polyèdre irrégulier', FALSE), (294, 29, 'que le monde a été créé selon des lois entièrement mathématiques', TRUE),
(301, 30, 'est à faire pour le lendemain', FALSE), (302, 30, 'a été emporté par une mouette quand elle est allée au bord de la mer', FALSE), (303, 30, 'est à rendre pour la semaine suivante', FALSE), (304, 30, 'aurait déjà dû être rendu depuis une semaine au moins', TRUE),
(311, 31, 'un monde de fantômes', FALSE), (312, 31, 'une matière qui va lui rapporter des points', FALSE), (313, 31, 'pratiquée par Booba et Kaaris pour s\'améliorer en octogone', FALSE), (314, 31, 'une matière scolaire comme les autres', TRUE),
(321, 32, 'parlent en dormant mais uniquement en grec attique', FALSE), (322, 32, 'existent dans notre réalité', TRUE), (323, 32, 'sont aussi inutiles que les figures géométriques', FALSE), (324, 32, 'vivent comme les espèces animales', FALSE),
(331, 33, 'parce qu\'il a décidé d\'aller à la pêche en mer', FALSE), (332, 33, 'parce qu\'il a toujours rêvé d\'être gladiateur', FALSE), (333, 33, 'pour montrer à Laurence qu\'il est impossible d\'attraper un nombre', TRUE), (334, 33, 'parce qu\'il veut modifier la décoration de la pièce', FALSE),
(341, 34, 'd\'essayer d\'attraper le nombre 3 avec le filet, mais les mailles sont trop grandes', FALSE), (342, 34, 'de confondre le chiffre trois et le nombre trois', TRUE), (343, 34, 'de montrer à son grand-père trois doigts de sa main droite', FALSE), (344, 34, 'de montrer son ombre à son grand-père', FALSE),
(351, 35, 'un alphabet syriaque', FALSE), (352, 35, 'de jolis dessins décoratifs qui n\'ont pas de sens', FALSE), (353, 35, 'des équations mathématiques incompréhensibles pour Laurence', FALSE), (354, 35, 'différents dessins pour représenter les nombres de un à neuf', TRUE),
(361, 36, '178', FALSE), (362, 36, '89002674', FALSE), (363, 36, '4', TRUE), (364, 36, 'deux mètres', FALSE),
(371, 37, 'des nombres décimés', FALSE), (372, 37, 'des nombres irrationnels', FALSE), (373, 37, 'des entiers naturels', TRUE), (374, 37, 'des nombres', FALSE),
(381, 38, 'ont été inventés il y a 5000 ans.', FALSE), (382, 38, 'ont effrayé les savants qui les considéraient comme des entités absurdes', TRUE), (383, 38, 'n\'ont jamais posé le moindre problème de compréhension aux savants', FALSE), (384, 38, 'poussent sur les arbres quand il fait très froid', FALSE),
(391, 39, 'un nombre qui ne vit que la nuit', FALSE), (392, 39, 'un nombre qui n\'a aucune utilité', FALSE), (393, 39, 'un nombre qui a une partie réelle et une partie imaginaire', TRUE), (394, 39, 'un nombre en forme de figurine pour jouer au warhammer', FALSE),
(401, 40, 'l\'imagination a été inutile', FALSE), (402, 40, 'l\'imagination a joué un rôle capital', TRUE), (403, 40, 'les animaux de la forêt ont été un obstacle non négligeable', FALSE), (404, 40, 'I\'USS Entreprise et Darnell ont joué un grand rôle', FALSE),
(411, 41, 'comptaient uniquement sur leurs doigts', FALSE), (412, 41, 'comptaient leurs cheveux pour les nombres supérieurs à 10', FALSE), (413, 41, 'utilisaient parfois des \"cailloux\"', FALSE), (414, 41, 'faisaient des encoches sur des ossements', TRUE),
(421, 42, 'des millions d\'années', FALSE), (422, 42, '5000 ans tout au plus', TRUE), (423, 42, '50 000 ans', FALSE), (424, 42, 'l\'invention du grille-pain', FALSE),
(431, 43, 'de la Grèce antique', FALSE), (432, 43, 'de la même époque que la ville de Gottham', FALSE), (433, 43, 'de la préhistoire', TRUE), (434, 43, 'de l\'époque de Charlemagne', FALSE),
(441, 44, 'les Incas', FALSE), (442, 44, 'les Grecs', FALSE), (443, 44, 'les Soixantins', FALSE), (444, 44, 'les Babyloniens', TRUE),
(451, 45, 'un chevalier de la Table Ronde', FALSE), (452, 45, 'l\'un des sept sages de la Grèce antique', TRUE), (453, 45, 'un ami de Platon', FALSE), (454, 45, 'un Egyptien célèbre', FALSE),
(461, 46, 'recherchent des vérités éternelles pour comprendre l\'univers', TRUE), (462, 46, 'passent le temps pour s\'amuser', FALSE), (463, 46, 'cherchent uniquement à résoudre des problèmes concrets et pratiques', FALSE), (464, 46, 'étudient le comportement des animaux', FALSE),
(471, 47, 'au Vle siècle avant Jésus-Christ', TRUE), (472, 47, 'au temps des moulins à café', FALSE), (473, 47, 'à l\'époque romaine', FALSE), (474, 47, 'au XXe siècle', FALSE),
(481, 48, 'uniquement ce que nous percevons avec nos yeux', FALSE), (482, 48, 'ce que nous découvrons et prouvons par le raisonnement', TRUE), (483, 48, 'ce qui fait mal aux pieds', FALSE), (484, 48, 'ce que pense la majorité des gens', FALSE),
(491, 49, 'le monde obéit au hasard', FALSE), (492, 49, 'tout n\'est que désordre et chaos', FALSE), (493, 49, 'tout est nombre', TRUE), (494, 49, 'tout a été inventé par des dieux fourbes, capricieux et colériques', FALSE),
(501, 50, 'utilisaient déjà la virgule', FALSE), (502, 50, 'arrondissaient les nombres pour n\'utiliser que des nombres entiers', FALSE), (503, 50, 'employaient la notion de rapport (ici, le \"rapport entre 10 et 18\")', TRUE), (504, 50, 'utilisaient un squelette de chameau', FALSE),
(511, 51, 'un nombre qui ne peut pas s\'écrire sous forme de rapport', TRUE), (512, 51, 'un animal avec une carapace et des cornes', FALSE), (513, 51, 'un nombre uniquement précédé du signe \"-\"', FALSE), (514, 51, 'un nombre qui n\'existe pas', FALSE),
(521, 52, 'ont facilement admis l\'existence des nombres irrationnels', FALSE), (522, 52, 'ont difficilement admis l\'existence des nombres irrationnels', TRUE), (523, 52, 'ont fait beaucoup de trottinette', FALSE), (524, 52, 'ont admis l\'existence des liconres à cinq pattes', FALSE),
(531, 53, 'une sorte de journaliste qui rapporte les faits divers', FALSE), (532, 53, 'un homme qui écrit uniquement des pièces de théâtre', FALSE), (533, 53, 'un \"ami de la sagesse\"', TRUE), (534, 53, 'un membre de la famille de maître Xixunfushami', FALSE),
(541, 54, 'Athènes', TRUE), (542, 54, 'Rome', FALSE), (543, 54, 'New-Yok', FALSE), (544, 54, 'Paris', FALSE),
(551, 55, 'un jardin où l\'on se promène en silence pour ne pas déranger ceux qui écoutent l\'herbe pousser', FALSE), (552, 55, 'un lieu où l\'on peut discuter et réfléchir librement sur tout', TRUE), (553, 55, 'un espace où l\'on apprend à maîtriser un référentiel bondissant', FALSE), (554, 55, 'un château où viennent se mesurer les plus grands chanteurs de l\'époque', FALSE),
(561, 56, 'est uniquement ce que nous voyons', FALSE), (562, 56, 'est perceptible grâce à des lunettes infrarouges', FALSE), (563, 56, 'est une évidence qui n\'a pas à être discutée', FALSE), (564, 56, 'se situe nécessairement au-delà des apparences', TRUE),
(571, 57, 'ont réalisé des progrès scientifiques bien supérieurs à ceux de la Grèce antique', FALSE), (572, 57, 'ne sont pas allés beaucoup plus loin que les savants grecs', TRUE), (573, 57, 'ont découvert la formule de Panoram\'x', FALSE), (574, 57, 'se sont totalement désintéressés du savoir scientifique', FALSE),
(581, 58, 'tous les manuscrits grecs et latins ont été perdus', FALSE), (582, 58, 'de nombreux manuscrits latins ont été sauvés grâce au travail des moines copistes', TRUE), (583, 58, 'tous les manuscrits grecs et latins ont été conservés', FALSE), (584, 58, 'les chevaliers du roi Arthur ont protégé le savoir scientifique', FALSE),
(591, 59, 'parce que c\'était un touriste avide de nouveautés', FALSE), (592, 59, 'parce qu\'il voulait enrichir ses connaissances scientifiques en se rendant lui-même sur les lieux les plus importants de notre Histoire', TRUE), (593, 59, 'parce que c\'était un vendeur de voitures électriques ultra-connectées', FALSE), (594, 59, 'parce qu\'il avait n\'avait pas de domicile fixe', FALSE),
(601, 60, 'sont une somme sans intérêt de remarques désordonnées sur tout et n\'importe quoi', FALSE), (602, 60, 'des brouillons de poèmes et de romans', FALSE), (603, 60, 'un trésor d\'une valeur inestimable sur le plan scientifique', TRUE), (604, 60, 'des notes pour un guide touristique gastronomique', FALSE),
(611, 61, 'Rome', FALSE), (612, 61, 'Alexandrie', TRUE), (613, 61, 'Le Havre', FALSE), (614, 61, 'Marseille', FALSE),
(621, 62, 'écrasé par une tortue lâchée par un aigle au-dessus de sa tête', FALSE), (622, 62, 'd\'un accident de voiture', FALSE), (623, 62, 'd\'une longue maladie', FALSE), (624, 62, 'assassiné par un soldat romain alors qu\'il faisait de la géométrie', TRUE),
(631, 63, 'le maître de la géométrie à l\'époque d\'Alexandrie', TRUE), (632, 63, 'le chien d\'Alexandre', FALSE), (633, 63, 'un éleveur de chameaux', FALSE), (634, 63, 'le maître du calcul à l\'époque d\'Alexandrie', FALSE),
(641, 64, 'noyée sous un tsunami', FALSE), (642, 64, 'détruite par un incendie', TRUE), (643, 64, 'conservée intacte jusqu\'à nos jours', FALSE), (644, 64, 'dévastée par une invasion de rats', FALSE),
(651, 65, 'Rome', FALSE), (652, 65, 'Washington', FALSE), (653, 65, 'Bagdad', TRUE), (654, 65, 'Jérusalem', FALSE),
(661, 66, 'l\'utilisation de la calculatrice', FALSE), (662, 66, 'l\'écriture des nombres', TRUE), (663, 66, 'le tonneau', FALSE), (664, 66, 'la virgule pour les nombres décimaux', FALSE),
(671, 67, 'à l\'âge de fer', FALSE), (672, 67, 'au Ve siècle', FALSE), (673, 67, 'au XVIIIe siècle', FALSE), (674, 67, 'au VIIle siècle', TRUE),
(681, 68, 'n\'ont joué aucun rôle dans l\'histoire des mathématiques', FALSE), (682, 68, 'sont en partie à l\'origine de notre écriture des nombres', TRUE), (683, 68, 'ne s\'intéressaient pas du tout aux nombres', FALSE), (684, 68, 'ne s\'intéressaient qu\'à l\'étude des nénuphars', FALSE),
(691, 69, 'le mot arabe \"sifr\"', TRUE), (692, 69, 'une déformation en Ancien Français du mot \"chiffon\"', FALSE), (693, 69, 'un mot indien qui voulait dire \"souffrir\"', FALSE), (694, 69, 'inconnue', FALSE),
(701, 70, 'n\'a joué aucun rôle', FALSE), (702, 70, 'a eu une importance capitale', TRUE), (703, 70, 'n\'a eu que peu d\'importance', FALSE), (704, 70, 'est un mensonge répété par tout le monde', FALSE),
(711, 71, 'par l\'Angleterre', FALSE), (712, 71, 'par l\'Espagne et l\'Italie', TRUE), (713, 71, 'par la Chine', FALSE), (714, 71, 'par un tunnel sous-marin', FALSE),
(721, 72, 'au siècle de Rahan fils de Crâo', FALSE), (722, 72, 'au XVIIIe siècle', FALSE), (723, 72, 'au Vile siècle', FALSE), (724, 72, 'au XIIe siècle', TRUE),
(731, 73, 'ne doivent pas être étudiées', FALSE), (732, 73, 'doivent être étudiées pour nous rapprocher des vérités éternelles', TRUE), (733, 73, 'sont une illusion d\'optique', FALSE), (734, 73, 'sont la seule et unique discipline à étudier', FALSE),
(741, 74, 'd\'un des plus grands mathématiciens du Moyen Age', TRUE), (742, 74, 'd\'une ville de Sicile', FALSE), (743, 74, 'd\'une statue célèbre en Italie', FALSE), (744, 74, 'du chat de l\'empereur Frédéric II', FALSE),
(751, 75, 'par les Turcs', TRUE), (752, 75, 'par les Grecs', FALSE), (753, 75, 'par les coléoptères longicornes xylophages', FALSE), (754, 75, 'par les Indiens', FALSE),
(761, 76, 'l\'Antiquité', FALSE), (762, 76, 'la Renaissance', TRUE), (763, 76, 'les soldes', FALSE), (764, 76, 'le siècle classique', FALSE),
(771, 77, 'des textes chinois', FALSE), (772, 77, 'des textes grecs, notamment ceux de Platon', TRUE), (773, 77, 'des textes en Ancien Français jusqu\'alors inconnus', FALSE), (774, 77, 'les traces d\'une civilisation engloutie appelée l\'Atlantide', FALSE),
(781, 78, 'le spécialiste d\'une seule discipline', FALSE), (782, 78, 'un expert en arts martiaux asiatiques', FALSE), (783, 78, 'un \"homme universel\" qui s\'intéresse à tout', TRUE), (784, 78, 'un moine qui vit en dehors du monde, en solitaire', FALSE),
(791, 79, 'les deux clowns d\'un cirque célèbre au XVIe siècle', FALSE), (792, 79, 'les inventeurs des \"nombres imaginaires\"', TRUE), (793, 79, 'les inventeurs de la lettre \"x\" pour le calcul littéral', FALSE), (794, 79, 'les inventeurs du signe \"+\"', FALSE),
(801, 80, 'ont toujours existé', FALSE), (802, 80, 'ont été inventés au XXe siècle', FALSE), (803, 80, 'ont été inventés entre le XVe et le XVIIe siècle', TRUE), (804, 80, 'ont été trouvés dans une grotte préhistorique', FALSE),
(811, 81, 'n\'a joué aucun rôle', FALSE), (812, 81, 'a eu une importance capitale', TRUE), (813, 81, 'a joué un rôle de premier plan dans un film de science-fiction très connu', FALSE), (814, 81, 'a joué un rôle important, mais qu\'il ne faut pas exagérer', FALSE),
(821, 82, 'Diophante', FALSE), (822, 82, 'Descartes', TRUE), (823, 82, 'Al Khwarizmi', FALSE), (824, 82, 'Bobby', FALSE),
(831, 83, 'une pratique occulte pour lire l\'avenir', FALSE), (832, 83, 'une technique de dressage d\'animaux', FALSE), (833, 83, 'l\'ensemble des méthodes de calculs qui visent à déterminer des valeurs inconnues dans une égalité mathématique', TRUE), (834, 83, 'l\'ensemble des méthodes de mesure utilisées par les architectes pour construire de grands magasins', FALSE),
(841, 84, 'décrire la gravitation universelle', TRUE), (842, 84, 'comprendre la structure des métaux', FALSE), (843, 84, 'gagner beaucoup d\'argent sans rien faire', FALSE), (844, 84, 'calculer le volume d\'une sphère', FALSE),
(851, 85, 'n\'est plus du tout utilisé', FALSE), (852, 85, 'n\'est utilisé que par les joueurs de go', FALSE), (853, 85, 'est de plus en plus utilisé', TRUE), (854, 85, 'n\'est pas plus utilisé que lors des périodes précédentes', FALSE),
(861, 86, 'décrire de plus en plus de phénomènes dans la nature', TRUE), (862, 86, 'décrire de moins en moins de phénomènes dans la nature', FALSE), (863, 86, 'espérer faire parler les chiens dans un avenir proche', FALSE), (864, 86, 'uniquement décrire les phénomènes astronomiques', FALSE),
(871, 87, 'toujours très en retard', FALSE), (872, 87, 'très souvent en avance', TRUE), (873, 87, 'parfois en forme de bâtonnet', FALSE), (874, 87, 'toujours fausses', FALSE),
(881, 88, 'la forme d\'une table à repasser', FALSE), (882, 88, 'de multiples dimensions', TRUE), (883, 88, 'deux longueurs, trois largeurs, et deux fois plus de profondeur', FALSE), (884, 88, 'une infinité de dimensions', FALSE),
(891, 89, 'de tout prévoir', FALSE), (892, 89, 'de prévoir très peu d\'événements ou de phénomènes', FALSE), (893, 89, 'un nombre croissant de phénomènes mais avec une marge d\'incertitude', TRUE), (894, 89, 'de communiquer secrètement avec les chèvres', FALSE),
(901, 90, 'déterminer la place du lit du patient', FALSE), (902, 90, 'établir la formule chimique idéale de son alimentation', FALSE), (903, 90, 'déterminer le nombre de soignants nécessaires à sa guérison', FALSE), (904, 90, 'préciser les doses et les fréquences des chimiothérapies administrées au patient', TRUE),
(911, 91, 'a été projetée contre un mur', FALSE), (912, 91, 'a commencé à découvrir qui était réellement son père', TRUE), (913, 91, 'a adopté un labrador', FALSE), (914, 91, 'a appris à lire, écrire et parler le mandarin', FALSE),
(921, 92, 'son père avait vécu sous la menace d\'un danger imminent', TRUE), (922, 92, 'son grand-père était un champion d\'aviron', FALSE), (923, 92, 'son père était le descendant d\'un célèbre pharaon', FALSE), (924, 92, 'elle était peut-être la reine d\'une cité engloutie', FALSE),
(931, 93, 'à étudier jour et nuit les carnets de son père', TRUE), (932, 93, 'à chercher les pièces d\'un puzzle offert par son père à un de ses anniversaires', FALSE), (933, 93, 'à se fabriquer un costume de super héroïne', FALSE), (934, 93, 'à collectionner les figurines de grands savants', FALSE),
(941, 94, 'un célèbre compositeur du XVIIIe siècle', FALSE), (942, 94, 'le cousin de Silverbach', FALSE), (943, 94, 'un célèbre mathématicien du XVIIe siècle', TRUE), (944, 94, 'le nom d\'un livre d\'alchimie', FALSE),
(951, 95, 'un acteur de cinéma', FALSE), (952, 95, 'un grand mathématicien du XXe siècle', TRUE), (953, 95, 'un biologiste', FALSE), (954, 95, 'un peintre', FALSE),
(961, 96, 'n\'a pas encore été résolu', TRUE), (962, 96, 'a été résolu', FALSE), (963, 96, 'a été perdu lors d\'une tempête', FALSE), (964, 96, 'a été un sujet de méditation pour les chevaliers templiers', FALSE),
(971, 97, 'n\'a pas pu rentrer chez elle car sa porte était fermée', FALSE), (972, 97, 'a ouvert la porte du garage', FALSE), (973, 97, 'est entrée dans un monde inconnu', TRUE), (974, 97, 'a perdu ses clefs', FALSE),
(981, 98, 'est une ville du nord du Canada', FALSE), (982, 98, 'est une cité marine de l\'antiquité grecque', FALSE), (983, 98, 'un film de science-fiction', FALSE), (984, 98, 'la mystérieuse cité où se trouverait le père de Laurence', TRUE),
(991, 99, 'renonce à chercher son père', FALSE), (992, 99, 'se met à la recherche de son père grâce aux carnets de celui-ci', TRUE), (993, 99, 'devient une célèbre actrice de cinéma', FALSE), (994, 99, 'quitte Marseille pour un voyage interstellaire', FALSE),
(1001, 100, 'les membres d\'une équipe de bobsleigh', FALSE), (1002, 100, 'les membres d\'un très célèbre groupe de musique celtique alternative', FALSE), (1003, 100, 'les auteurs de la collection Mathéopolis', TRUE), (1004, 100, 'des dresseurs de gnous', FALSE);

SET FOREIGN_KEY_CHECKS = 1;
